title: Andrea Monterrubio
logo: images/headshot_crop.jpg
description: Recent Data Analysis Graduate | Seeking Opportunities to Grow
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
